steps:
  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CELADON_URL=${_CELADON_URL}'
      - '-t'
      - 'us.gcr.io/$PROJECT_ID/web-client:$COMMIT_SHA'
      - '.'
  # Push the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us.gcr.io/$PROJECT_ID/web-client:$COMMIT_SHA']
  # Deploy to cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'web-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-client:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images:
  - 'us.gcr.io/$PROJECT_ID/web-client:$COMMIT_SHA'
