FROM node:19-alpine3.16
WORKDIR /app

ARG CHAIN_ID
ARG CHAIN_GRPC
ARG CELADON_URL

ENV APP_ENV=production
ENV PUBLIC_SECRET_NETWORK_CHAIN_ID=$CHAIN_ID
ENV PUBLIC_SECRET_NETWORK_GRPC_URL=$CHAIN_GRPC
ENV CELADON_URL=$CELADON_URL

COPY package.json ./
RUN npm install -g npm
RUN npm install
COPY . .
RUN npm run build
CMD ["node", "dist/index.js"]