name: CI/CD

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: web-staging
  PUBLIC_SECRET_NETWORK_CHAIN_ID: 'secret-4'
  PUBLIC_SECRET_NETWORK_GRPC_URL: 'https://grpc.mainnet.secretsaturn.net'
  CELADON_URL: 'http://127.0.0.1:3000'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js 18.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm install
          npx playwright install-deps
          npx playwright install
      - name: Test
        run: pnpm run test

  trigger-build:
    needs: [lint, e2e]
    name: Build & Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.RUN_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Trigger build
        run: gcloud beta builds triggers run build-$SERVICE_NAME --region=global
