name: Playwright (E2E Tests)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PUBLIC_SECRET_NETWORK_CHAIN_ID: 'secret-4'
  PUBLIC_SECRET_NETWORK_GRPC_URL: 'https://grpc.mainnet.secretsaturn.net'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js 18.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm install
          npx playwright install-deps
          npx playwright install
      - name: Test
        run: pnpm run test
